import argparse
import json
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Analyze a single traffic image for Vietnamese traffic violations."
    )
    parser.add_argument("image", help="Path to the input image.")
    parser.add_argument(
        "--scene-config",
        help="Optional JSON file with lane, no-parking-zone, and stop-line geometry.",
    )
    parser.add_argument(
        "--annotate",
        help="Optional output path for an annotated detection image.",
    )
    parser.add_argument(
        "--segment-dir",
        help="Optional directory for violated-object crops, masks, and overlays.",
    )
    parser.add_argument(
        "--output",
        help="Optional path to save the JSON analysis result.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.35,
        help="GroundingDINO box threshold.",
    )
    parser.add_argument(
        "--text-threshold",
        type=float,
        default=0.25,
        help="GroundingDINO text threshold.",
    )
    parser.add_argument(
        "--vlm",
        choices=["none", "qwen"],
        default="none",
        help="Optional VLM reasoner to run after the rule engine.",
    )
    parser.add_argument(
        "--qwen-model",
        default="Qwen/Qwen2.5-VL-3B-Instruct",
        help="Hugging Face model id for Qwen2.5-VL.",
    )
    parser.add_argument(
        "--vlm-max-new-tokens",
        type=int,
        default=512,
        help="Maximum number of tokens generated by the VLM.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    from illegal_detector.traffic_violation_pipeline import TrafficViolationPipeline

    vlm_reasoner = None
    if args.vlm == "qwen":
        from illegal_detector.vlm_reasoner import QwenVLReasoner

        vlm_reasoner = QwenVLReasoner(
            model_id=args.qwen_model,
            max_new_tokens=args.vlm_max_new_tokens,
        )

    pipeline = TrafficViolationPipeline(
        vlm_reasoner=vlm_reasoner,
        threshold=args.threshold,
        text_threshold=args.text_threshold,
    )
    result = pipeline.analyze(
        image_path=args.image,
        scene_config_path=args.scene_config,
        annotate_path=args.annotate,
        segment_dir=args.segment_dir,
        run_vlm=args.vlm != "none",
    )
    result_json = json.dumps(result, ensure_ascii=False, indent=2)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(result_json, encoding="utf-8")

    print(result_json)


if __name__ == "__main__":
    main()
